---
# tasks file for MeshAgent
- name: Stat MeshAgent configuration file
  stat:
    path: /usr/local/mesh/meshagent.msh
  register: meshagentConfig

- name: Download meshagent install file
  get_url:
    url: https://puppet.arc.rice.edu/meshagents?script=1
    dest: /root/meshinstall.sh
    mode: 0700
    owner: root
    group: root
    validate_certs: "{{ meshValidateCert }}"
  notify: Install meshagent
  when: meshKey | length > 0 and
        not meshagentConfig.stat.exists
